name: Build Tweak
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          echo "export THEOS=~/theos" >> ~/.zshrc
          source ~/.zshrc
      - name: Compile
        run: |
          source ~/.zshrc
          make clean
          make
      - name: Upload dylib
        uses: actions/upload-artifact@v4
        with:
          name: honguo-dylib
          path: .theos/obj/arm64/honguo.dylib